### ISSUE TITLE
ptex2pdf で "予 定.tex" が処理できない

### ISSUE THREAD

**Issue by aminophen** [texjporg/ptex2pdf#10]
「Windows 環境で ptex2pdf v0.9 を使用して "予 定.tex" を処理しようとすると dvipdfmx でエラーが発生して "予 定.pdf" が作成できない」というのが、TeX Wiki に書かれています。

ptex2pdf で subdirectory を読めるようにした #6 における Windows の `\` separator を考慮した私の変更が原因だそうです：

~~~~ lua
 bname = string.gsub(bname, "^.*[/\\](.*)$", "%1")
~~~~

を以下のようにコメントアウトすると処理できるようになるようです。

~~~~ lua
 --bname = string.gsub(bname, "^.*[/\\](.*)$", "%1")
~~~~

しかし、これは Windows の subdirectory を考えると `\\` を gsub で取り除くことが必要なので悩みます。「subdirectory は `/` で書かなければならない」と決めることにしましょうか。

＃ 今回はたまたま Wiki を見て気づきましたが、この issue か forum に書き込んでくれればいいのに。

**Comment by aminophen** [comment]
あるいは cjk-gs-integrate win32 support で私が書いたような `Encode::encode` と `Encode::decode` の機能を使えば回避できるかもしれません。のちほどもう少し調べてみます。

**Comment by aminophen** [comment]
Lua によるエンコード変換は Lua 5.3 で utf8 が導入されたくらいで，LuaTeX に入っている Lua 5.2 では使えないようです。したがって，エンコード変換で回避するのは諦めます。

~~~~ lua
bname = string.gsub(bname, "^.*/.*)$", "%1")
~~~~

に直すしかないかもしれません。（これで安全かどうかはまだ不安ですが）

**Comment by aminophen** [comment]
ふとした思いつきですが

- string.gsub した結果，取り除かれた文字列が empty でなく，かつディレクトリならば → そのまま処理
- ディレクトリでなければ → 取り除く前の状態に復帰して処理

でいけそうです。あとでコードを書きます。

**Comment by aminophen** [comment]
2bf51fc6 で直せたように思います。テストお願いします。

**Comment by aminophen** [comment]
一つミスっていたのを 671b029 で直しました。

**Comment by aminophen** [comment]
ZR さんのコードのほうが良かったので 2e7d609 で置き換えました。参考：

- https://gist.github.com/zr-tex8r/0bbb1e25f6c4b977244d6cd39a501674
- https://gist.github.com/zr-tex8r/96dc09a6696784d75fb4169d5c9cd8bc

**Comment by norbusan** [comment]
ありがとうございます。
バーションは0.9.1じゃなくて、1.0にして、その後1.1など。他のアイデアはYYYYMMDDのバーション？どう思いますか？

**Comment by aminophen** [comment]
cjk-gs-integrate みたいに 20170603.0 のようにしてよければ，その方がわかりやすくて良いです。

**Comment by norbusan** [comment]
そそそ！次のリリースをそのとおりにしましょう！

**Comment by aminophen** [comment]
了解です。コードを書いてみます。

**Comment by norbusan** [comment]
別に今必要じゃありません。僕はリリースの前cjk-gsのコードをコッピーします。

**Comment by aminophen** [comment]
私のほうで release.sh をコピーしておきました。

**Comment by aminophen** [comment]
ptex2pdf のリリースをお願いしてもよろしいでしょうか？

**Comment by norbusan** [comment]
了解です！
