### ISSUE TITLE
"Multiple filename arguments, only one can be processed, exiting." が出るらしい

### ISSUE THREAD

**Issue by kmaed** [texjporg/ptex2pdf#11]
[最新版の ptex2pdf でエラーが発生する](https://texwiki.texjp.org/?cmd=diff&page=Emacs%2FTeX%20mode)らしいのですが，どなたか再現できますでしょうか．少なくとも自分の Linux 環境では 20170604.0 で Emacs の TeX mode から，ターミナルからともに問題なく動いているので，よくわかりません．書いている本人にもう少し詳しく説明してほしいところですが，とりあえず．

**Comment by aminophen** [comment]
再現しました。C-c C-f すると

~~~~
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

~~~~
c:\Users\aminophen\test>ptex2pdf -u -l -ot "-kanji=utf8 -no-guess-input-enc -synctex=1 -interaction=nonstopmode" "\nonstopmode\input" "tabglue.tex"
ptex2pdf -u -l -ot "-kanji=utf8 -no-guess-input-enc -synctex=1 -interaction=nonstopmode" "\nonstopmode\input" "tabglue.tex"
Multiple filename arguments, only one can be processed, exiting.

c:\Users\aminophen\test>
~~~~

どこからか `"\nonstopmode\input"` がわいてきています。これは ptex2pdf のバグの類ではないです。Emacs のマクロがこれを追加している理由がよくわかりません。

**Comment by aminophen** [comment]
Multiple filename arguments, only one can be processed, exiting.

のエラーは 90b66b5 で追加されたものです。これより前のバージョンでは、複数の「オプションとみなされなかった引数」が見つかった場合は、「最後のひとつ」だけを filename とみなして処理していたはずです。（つまり `"\nonstopmode\input"` は silently ignored な状態）

**Comment by aminophen** [comment]
エラーで落としていたところを

~~~~ lua
    if filename == "" then
      filename = this_arg
    else
      print("Multiple filename arguments? OK, I'll take the latter one.")
      filename = this_arg
    end
~~~~

とすれば、Emacs のマクロのような `"\nonstopmode\input"` がある場合でも処理可能です。

**Comment by aminophen** [comment]
a29f0dd で、複数の「オプションとみなされなかった引数」が見つかった場合に

- 最後のひとつを filename とみなす
- それより前にあったものは、tex のコマンド呼び出し時に filename より前にそのまま渡す

としてみました。これで、たとえば[これ](https://github.com/h-kitagawa/plext_test/blob/master/test-tate.tex)のような簡単なケースであれば

~~~~ tex
% test-tate.tex
\let\BASEDIR\tate
\input test
~~~~

を準備しなくても、単に

~~~~
ptex2pdf -l "\let\BASEDIR\tate" "\input" test
~~~~

でパッチ完了になって、便利かもしれません。

なお、たとえば

~~~~
ptex2pdf -l "\RequirePackage{exppl2e}" "\input" test.tex
~~~~

みたいな複雑なパッチをあてる場合には（ptex2pdf は test.dvi を期待するが、実際にできるのは「最初に読まれたファイルの basename」すなわち exppl2e.dvi なので）ストップしますが、ファイル名を決定するのが困難ですから、対処しなくてよいと思っています。

**Comment by kmaed** [comment]
なるほど．`"\nonstopmode\input"` はこうしておくと TeX エンジンが実行プログラムならば nonstopmode にしてからあとのファイルを読み込む動作になるので tex-mode ではデフォルトで追加するようです．前からあったのか覚えていませんが，--interaction= で今はいけるのですね．私は nonstopmode にしたくないので `(setq tex-start-commands nil)` をつっこんでいたせいで全く気付かなかったようです．

TeX は引数がファイル名ならそれを \input するけれども，コントロールシーケンスがくると単に以降の文字列を順に読み込んでいく動作になるので，ptex2pdf を TeX エンジンだと思って扱うと後者の場合に問題になるわけですね．極端な話，`ptex2pdf '\relax a\bye'` で texput.pdf ができるという期待は裏切られるのですね．まあ，ほとんど需要ないでしょうけれども．

……などと書いていたら追加の返信いただきました． a29f0dd の仕様で大抵はよさそうですね．

**Comment by aminophen** [comment]
もしかして： tex の -jobname オプションを使うようにすれば

`ptex2pdf '\relax a\bye'`

みたいなケースにも対処できる？

**Comment by kmaed** [comment]
>  tex の -jobname オプションを使う

具体的な仕様によりますが，危ない香りも感じます．

**Comment by aminophen** [comment]
確かに、ptex2pdf には「kpsewhich でファイルを探す」という処理が入っていますので、もし対処しようとすると「それがファイル名なのか TeX のコントロールシーケンス絡みなのか」を事前に判断しないといけなかったですね。そこまでは入れない方が安全そうです。

**Comment by aminophen** [comment]
I uploaded the new version (20170622.0) to CTAN.
