### ISSUE TITLE
デフォルトエンジンの変更（ポストインストール）

### ISSUE THREAD

**Issue by abenori** [texjporg/ptex2pdf#8]
TeXworksにpTeX関連の設定が入るようにしていただきましたが，デフォルトのエンジンがpdfLaTeXのままのようです．これをpLaTeX (ptex2pdf)にしてもらうことは可能でしょうか？

````
texworks/TUG/TeXworks.iniに
[General]
defaultEngine=pLaTeX (ptex2pdf)
````

とすればよいのかと思います．

**Comment by norbusan** [comment]
ちょっと疑ってます。これまでデフォルトの変更しなくて、新しい設定だけ追加しましたが、デフォルトの変更は違うレベルですよね。

**Comment by abenori** [comment]
そうですね，「するべきか」というのは悩みます．そこの判断まで込めて議論したい，という感じです．

**Comment by aminophen** [comment]
前提として、OS の言語が日本語の場合に post-install でデフォルトを変えるという話ですよね？

日本で TeXworks を使っている人の大半が pLaTeX (ptex2pdf) を使っているならば、デフォルトの変更してもよいかもしれないと思います。upLaTeX と比べてどちらが多いかとか、日本で pdfLaTeX ばかり使っている人の割合は全く知りません。

**Comment by kuroky49** [comment]
その通りです＞「前提として……」

lang=ja* のときに限って，ptex2pdf のポストインストールスクリプトでは「pLaTeX (ptex2pdf)」などの日本語用設定を施しているので，その流れの中で，デフォルトのタイプセットを「pLaTeX (ptex2pdf)」にしてもらえませんか？というお話です．なので，世界の大多数の人にとっては「pdfLaTeX」のままで，日本語メインの人には「pLaTeX (ptex2pdf)」がデフォルトになり，好ましい設定だと思います．

pLaTeX がよいか upLaTeX がよいか，というのは難しい話（ポリシーの問題）ですが，個人的には pLaTeX のほうがよいと思っています．

**Comment by norbusan** [comment]
Karlさんに説明して、相談をききました。

**Comment by norbusan** [comment]
とりあえずデフォルトの変更しましょう。
ですが、またTeX Worksの開発者に連絡して、他のいい方法を探しましょう。

**Comment by norbusan** [comment]
ちょっと探しましたが、みつけていません：どうやってcross-platformにTeXworks.confをみつけれますか？

- linux: `XDG_CONF_HOME/TUG/TeXworks.conf`
- windows: ???
- Mac: ???

そうして、Macで同じフォマットを使われていますか？`.plist`じゃないかな？

**Comment by aminophen** [comment]
windows で探しましたが、TeXworks.ini のようなデフォルト設定用ファイルを見つけられませんでした。設定の追加したのは C:\Users\ユーザ名\TeXworks\configuration\tools.ini ですけど、これとは別ですね。

**Comment by aminophen** [comment]
あっ、ようやくわかりました。%HKEY_CURRENT_USER%\Software\TUG\TeXworks にあります。

**Comment by aminophen** [comment]
regedit.exe でレジストリをみたときのものを画像で貼ります。defaultEngine という key に対応する value がデフォルトです。もちろん、レジストリの変更には管理者権限が必要です。

![regedit-tug](https://cloud.githubusercontent.com/assets/9957466/21482560/df99c69e-cbb8-11e6-8552-01c3d4791a5f.png)

**Comment by aminophen** [comment]
default ではこのようにレジストリを使っているから難しいです。でも、代わりの方法があります。

C:\texlive\2016\tlpkg\texworks\texworks-setup.ini

というファイルを作って、その中に

~~~~
inipath = ./twdata
libpath = ./twdata
~~~~

と書いておくと、レジストリを使いません。代わりに

C:\texlive\2016\tlpkg\texworks\twdata\TeXworks.ini

の設定ファイルを読み込ませることができます。この設定ファイルはレジストリを dump したのと大体同じないようになっています。

~~~~
[General]
openDialogDir=C:/Users/Hironobu/Documents/
launchOption=1
syntaxColoring=LaTeX
autoIndent=\x306a\x3057
wrapLines=true
tabWidth=32
font="Migu 1M,12,-1,5,50,0,0,0,0,0"
language=en_US
scaleOption=1
previewScale=200
magnifierSize=2
circularMagnifier=true
binaryPaths=
defaultEngine=pLaTeX (ptex2pdf)
autoHideConsole=1
（以下省略）
~~~~

これなら管理者権限がいりません。

**Comment by norbusan** [comment]
ちょっと待ってください。この変更ptex2pdfのposinstallに行いたくないです。最初：どうやってこれまで設定の変更があるかないか確認できません。ptex2pdfのengineを追加は、設定変更がない場合だけ行います。レジストリを触りたくないし、特別の設定ファイルをつくりたくないし。Windows UACの関係も厳しそうです(admin - non-adminインスタレーション）などなどなど。

正直いうと、この変更は価値があると疑っています。

**Comment by aminophen** [comment]
私も、最初は pLaTeX (ptex2pdf) に変えるのは良いことだと思いましたが、レジストリを読んだり変えたりする必要があることに気づいて、難しいと感じました。ptex2pdf の postinstall に入れられるほど安全ではないと思います。

**Comment by abenori** [comment]
うちでは上に書いた通りtexworks/TUG/TeXworks.iniに書けば反映されているように見えます．より具体的には

C:\Users\[ユーザ名]\.texlive2016\texmf-config\texworks\configuration\TeXworks.ini

です．逆にレジストリの該当箇所は存在しませんでした．

**Comment by aminophen** [comment]
私の環境でも c:\Users\ユーザ名\.texlive2014 には texmf-config\texworks\configuration\TeXworks.ini があったので（一方 .texlive2015 と .texlive2016 には該当パスがありませんでした）、調べてみると

インストールした後に TeXworks を最初に起動したタイミングで .texliveYYYY 以下に該当ファイルを作る仕組みでした。私の手元で .texlive2015 と .texlive2016 に設定ファイルがなかったのは、その texworks.exe を起動したことがなかったからのようです。でも、なぜレジストリが書かれているのかよくわかりません。

**Comment by kmaed** [comment]
TeX Live 2015 が入っている Windows 8.1 マシンで試してみたところ，

 - bin\win32\texworks.exe を実行：レジストリはできない
 - tlpkg\texworks\texworks.exe を実行：レジストリができる

となりました．

**Comment by aminophen** [comment]
> TeX Live 2015 が入っている Windows 8.1 マシンで試してみたところ，
> - bin\win32\texworks.exe を実行：レジストリはできない
> - tlpkg\texworks\texworks.exe を実行：レジストリができる

全然気づいていませんでした。tlpkg の方が本体で、bin\win32 の方が wrapper ですね。私のレジストリの添付画像をよく見ると 2014 が出ているので、もしかすると 2014 年の TeXworks を  bin\win32\texworks.exe と tlpkg\texworks\texworks.exe の両方から起動したことがあるんでしょうか（2年前なので詳細不明）。

> TeX Live をインストールして普通に使っているとレジストリは使われないようになっている

かもしれないです。Mac のほうはどうでしょう？ 私が使える Mac は OS が古くて TeXworks はそもそも起動できませんのでどなたかお願いします。

**Comment by abenori** [comment]
止まってしまいましたが……．

改めて：TeX Live付属のTeXworksに対して，デフォルトエンジンをptex2pdfへと変更する，ということを検討していただけないでしょうか？方法としては，Windowsでは最初に書いた通り

    $TW_INIPATH/TUG/TeXworks.ini

に

    [General]
    defaultEngine=pLaTeX (ptex2pdf)

を加えてもらうことになります．（ファイルがなければ作成する．）上記でレジストリ云々という議論が交わされていますが，TeX Live付属のTeXworks（をbin/win32/texworks.exeから起動した場合）に対してはそれをする必要はないはずです．

（TeX Live付属でない場合（またはtlpkg/texworks/texworks.exeから起動した場合）はレジストリに保存されますが，それは相手にしなくてよいかと思います．）

**Comment by doraTeX** [comment]
美文書インストーラを作成するときに実験して判明した，MacのTeXworksの設定について情報を示しておきます。

# 日本語エンジン設定

`kpsewhich -var-value=TW_INIPATH` によって指示される場所に `tools.ini` を置いても設定が反映されませんでした。そこで，`TW_INIPATH` の値は無視して，`~/Library/TeXworks/configuration/` の中に `tools.ini` を置くと反映されました。

美文書第7版インストーラによって配置される `tools.ini` は[こちら](https://dl.dropboxusercontent.com/u/5807100/texworks/tools.ini)です。

# パス設定，デフォルトエンジン設定

TeX Live と Ghostscript のパス，およびデフォルトエンジン設定は，`~/Library/Preferences/org.tug.TeXworks.plist` に保存されています。このファイルは初回起動時に作成されます。

美文書第7版インストーラでは，インストール時にこのファイルが存在しない場合は，DVDからテンプレートとなる  plist ファイルをコピーします。なお，10.9以降では Preferences ディレクトリの plist ファイルを手動で変更した後には，`killall -SIGTERM cfprefsd` を実行しないと反映されませんので，実行しておきます。

```sh
$ cp -p <DVDのplist> ~/Library/Preferences/org.tug.TeXworks.plist
$ killall -SIGTERM cfprefsd
```

その上で，`defaults` コマンドを実行して，パス設定とデフォルトエンジン設定を次のように行っています。

```sh
$ defaults write org.tug.TeXworks binaryPaths -array-add "<TeXLiveのバイナリパス>"
$ defaults write org.tug.TeXworks binaryPaths -array-add "<Ghostscriptのパス>"
$ defaults write org.tug.TeXworks defaultEngine -string "pLaTeX (ptex2pdf)"
```

美文書第7版DVDに収録しているテンプレートとなる plist ファイルは[こちら](https://dl.dropboxusercontent.com/u/5807100/texworks/org.tug.TeXworks.plist)です。

このファイルはXMLファイルをバイナリ形式にコンバートしたものです。`plutil` コマンドでテキスト形式のXMLファイルと相互変換できます。

```sh
# テキスト形式に変換
$ plutil -convert xml1 hoge.plist
# バイナリ形式に変換
$ plutil -convert binary1 hoge.plist
```

テンプレートとなる上記の plist ファイルをテキスト形式に変換したものは[こちら](https://dl.dropboxusercontent.com/u/5807100/texworks/org.tug.TeXworks-text.plist)です。

**Comment by aminophen** [comment]
デフォルト以前の話ですみませんが、 @doraTeX さんによると現在の postinstall は tools.ini を探すのに以下のコードで動いています

~~~~ perl
  # how to find TeX Works
  # on Windows: we assume that the TL internal TeXWorks is used and
  #   search in TW_INIPATH
  # all other: we assume a system-wide TeXworks and use ~/.TeXworks
  my $toolsdir;
  if (win32()) {
    chomp( my $twini = `kpsewhich -var-value=TW_INIPATH` ) ;
    $toolsdir = "$twini/configuration";
  } else {
    $toolsdir = $ENV{'HOME'} . "/.TeXworks/configuration";
  }
  # print "toolsdir = $toolsdir\n";
  my $tools = "$toolsdir/tools.ini";
~~~~

これも動いてない、ということですか？

**Comment by doraTeX** [comment]
今手動で `tools.ini` を `~/.TeXworks/configuration/tools.ini` に置いてみましたが，やはり設定は反映されません。
というわけで，「動いてない」ということでよいと思います。

**Comment by aminophen** [comment]
> 「動いてない」ということでよいと思います。

ありがとうございます。既存の機能が Mac で機能しないのはよくない気がするので、なにかしらの対処をお任せしてよろしいでしょうか ＞ @doraTeX さん

改めてデフォルトの件ですが、私がレジストリの話を出してややこしくしてしまったのは申し訳ないです。あの辺りは TeX Live と関係ないということで無視してください。

それで、その発言以前のノルベルトさんの

> ちょっと疑ってます。これまでデフォルトの変更しなくて、新しい設定だけ追加しましたが、デフォルトの変更は違うレベルですよね。

が気になります。「新しい設定の追加」と「デフォルト変更」は ptex2pdf を使うための設定という点では同じですが、ptex2pdf にとって外のツールである TeXworks の設定のしかもデフォルトを、変更するというのはやりすぎでは、というのがノルベルトさんの背景にあるのかもしれないです。

**Comment by doraTeX** [comment]
> 既存の機能が Mac で機能しないのはよくない気がするので、なにかしらの対処をお任せしてよろしいでしょうか ＞ @doraTeX さん

対処しておきました。

**Comment by aminophen** [comment]
対処ありがとうございます。

デフォルトについての私の意見をはっきりさせると：TeX Live を日本語環境でインストールしたとき、デフォルトが ptex2pdf (pLaTeX) になってほしい、というのは同意しますが、それを「ptex2pdf の」postinstall で行うべきかというと、方法論として疑問が残ります。

**Comment by kuroky49** [comment]
TeX Live を日本語環境でインストールしたとき、デフォルトが pLaTeX (ptex2pdf) になってほしくて，それを行うのは，ptex2pdf の postinstall が最も自然で，適切であると思います．

それは，日本語対応エンジンリストを追加しているのが ptex2pdf の postinstall であり，pLaTeX (ptex2pdf) がデフォルトになるためには，ptex2pdf が確実にインストールされている必要があるので，ptex2pdf パッケージがデフォルト設定の役割を担うのは自然だからです．

**Comment by aminophen** [comment]
> ptex2pdf の postinstall が最も自然で，適切であると思います．

「どこかに処理を入れる必要があって、入れる場所を考えている」なら、仰るとおり ptex2pdf の postinstall が自然で適切であることはわかりますが、「入れること自体が適切であるかどうか」は別問題と思います。ノルベルトさんの意見がどうかは私にはわかりませんが。

**Comment by kuroky49** [comment]
「入れること自体が適切である」と黒木は思っています．

**Comment by aminophen** [comment]
既に書いたとおり

> ptex2pdf にとって外のツールである TeXworks の設定の、しかもデフォルトを変更する

と書き下してみると気持ち悪い気がしますし、postinstall に一方的に仕込んで「ユーザがそれを拒否する手段」が与えられない場合は押し付けがましいように私は思う訳です。

**Comment by aminophen** [comment]
「外のツールの設定をいじる」は MacTeX の postinstall で cjk-gs-integrate が走ることも同様ですから、ptex2pdf の postinstall で設定追加することには異論ありません。

が、デフォルト変更は「押し付けがましさ」が加わるという点で明らかに次元が違うので、もう少し慎重に考えるべきでは、と思います。

**Comment by kuroky49** [comment]
デフォルトがpdfLaTeXなのも押しつけであって，LANG=jaの環境の人（世界から見るとごく稀！）にとってはそれが満足できる結果ではない，と黒木は思います．

わざわざデフォルト設定を指定するのが気持ち悪いのであれば，別の選択肢を思いついたものとしては，tools.ini のエンジンリストを，pLaTeX (ptex2pdf) が先頭になるように設定する，というものがあります（ソースコードを読むとそれでよいように見えます）．それのほうがよいならまあそれでもよいかもしれません．

ちなみに，TeX Liveのインストールで，kanji-config-updmap-sys ipaex をデフォルトで実行していると思いますが，デフォルト設定として日本語のことを考えることが気持ち悪いとなると，kanji-config... も気持ち悪いということになってしまいそうですが，そんなことはないですよね？　ローカライズの仕組みを意図的に入れていないように見えるTeX Liveのインストーラで，可能な限りローカライズを考えて，LANG=jaの人が手間をかけずに日本語TeX環境を使えるようになってほしい，と思っています．

**Comment by aminophen** [comment]
> デフォルトがpdfLaTeXなのも押しつけであって

一つ以上ある限り何かがデフォルトになってしまうので（何か一つないと「空っぽ」になってしまう）、とりあえず pdfLaTeX なだけと思うので、さすがにそれは押しつけとは思いませんが

> 可能な限りローカライズを考えて，LANG=jaの人が手間をかけずに日本語TeX環境を使えるようになってほしい

は私も同意です。

> pLaTeX (ptex2pdf) が先頭になるように設定する

これはいい案だと思います。むしろ、デフォルト変更が不採用な場合だけでなく、採用の場合でも、先頭になってほしいように思います。

----

ちなみに私の見解では

> kanji-config-updmap-sys ipaex をデフォルトで実行

は「外」ではないです。kanji-config… も ipaex maps も両方 jfontmaps に入っていて、自分で自分の設定を追加しているだけだと思います。もし ipaex が押し付けがましいから嫌だといわれても、代わりの選択肢は「空っぽ（これだと dvipdfmx が全然使えない）」か「noEmbed または ipa を押し付ける」しかないわけですから、pdfLaTeX デフォルトの件と結局大差ないでしょう。

**Comment by kuroky49** [comment]
> pLaTeX (ptex2pdf) が先頭になるように設定

しても，デフォルトのエンジンは pdfLaTeX のままでした（ソースコード中で名前が直書きされていました）．訂正します．

**Comment by aminophen** [comment]
慎重な意見ばかり書いていますが、単にそれは悩んでいるだけなので（変えてから問題が起きるのはもうこりごりですよね？）、肯定的な立場からも考えてみます。

TeXworks.ini などの設定ファイルに

    [General]
    defaultEngine=pLaTeX (ptex2pdf)

とすればよいのはわかりますが、もう少し具体的なケースを：

- 設定ファイルに defaultEngine がない場合 → 追加

は当然お考えでしょうけど

- 設定ファイルが既に defaultEngine=upLaTeX (ptex2pdf) の場合
- 設定ファイルが既に defaultEngine=LuaLaTeX の場合
- 設定ファイルが既に defaultEngine=pdfLaTeX と明記している場合

それぞれどうすればよいのでしょう？ どれも起きうるケースだと思います。

**Comment by kuroky49** [comment]
tools.ini にエンジンリストを追加するかどうかの判断と同じ判断をしてくれればよいと思います．

**Comment by aminophen** [comment]
コードはどうにでもできますが（私も書けます）、ポリシーの問題です。こういうところを詰めておかないと、意図しないところでボロが出るものですよ。

~~~~ perl
    # policy: if ptex2pdf appears in any of the program entries, we
    # do nothing. Only otherwise we add new entries.
~~~~

と書いてありますが、この文言が私の質問に答えられるでしょうか？

**Comment by aminophen** [comment]
もっというと、たとえば「luahoge パッケージ」という project があったとして、luahoge というプログラムを TeXworks に追加してデフォルトに変更したとします。こういうものを検出した場合、ptex2pdf がとるべきデフォルトはなんでしょうか？ 実例を知りませんが、postinstall 同士が競合する可能性です。

**Comment by aminophen** [comment]
postinstall はインストールの最後だけでなく、アップデートの最後にも走ります。最悪のケースでは、アップデートの度にデフォルトが行ったり来たりするかもしれません。

**Comment by kuroky49** [comment]
具体的に書かないと分からないみたいなので書きますが，

```
# post action for ptex2pdf in TeX Live
# action carried out:
# - if the environment is Japanese or the installer is running in Japanese, then...
# - check for TeXworks tools.ini in
#   TW_INIPATH/configuration/tools.ini
# - if *not* available, initialize from the default plus Japanese stuff
# - if       available, read and try to add Japanese entries if not already there
```

と同様にすればよいでしょう（でNorbertには通じると思うのですが）．

一度もTeXworksを起動していなければ（＆他のインストールスクリプトが作成していなければ）TeXworks.ini は存在しないので，
- initialize the default as Japanese one that we desire to do
とすればよく，誰かがすでに書いているならば，
- read and try to set the default as Japanese one if not already there ==> fails to override
ということでよいでしょう．

**Comment by aminophen** [comment]
> 誰かがすでに書いているならば，
> read and try to set the default as Japanese one if not already there

具体的には、「Japanese one」が「already there」なのはどういう場合でしょうか。「ptex2pdf」は true でしょうけど、「LuaLaTeX」と書かれていたらこれは true なのでしょうか false なのでしょうか。最近はもっぱら LuaLaTeX を日本語に使っている人もいて、その人にとって ptex2pdf のインストール or アップデートの度に ptex2pdf に変わってしまうと苦痛だと思うなら、これも true にしたほうが良さそうな気がします。

**Comment by kuroky49** [comment]
LANG=ja であるときに，
- いかなるデフォルトエンジンの設定も書かれていなければ `pLaTeX (ptex2pdf)` がデフォルトエンジンになるように書く
- 任意のデフォルトエンジンの設定が書いてあれば，上書きしない

でよかろうと思っています．

**Comment by aminophen** [comment]
ということは

> read and try to set the default as Japanese one if not already there

は read and try to set the default as Japanese one if *degaultEngine is* not already there を意味するということですね。（さっきのだと if not の省略されている主語が read and try to set the default as Japanese one if *Japanese one is* not already there ともとれたので、何を意図したかようやく明快になりました）

**Comment by norbusan** [comment]
はい、デフォールトの変化ならば、下記の条件の場合だけで

- LANG=ja
- デファクトが設定されていない

という、デフォールトはpdflatexがあっても、変化しないように。

**Comment by aminophen** [comment]
> LANG=ja
> デファクトが設定されていない

私はこれに賛成します。

**Comment by abenori** [comment]
> はい、デフォールトの変化ならば、下記の条件の場合だけで
>
>  *   LANG=ja
>  *   デファクトが設定されていない 
>
> という、デフォールトはpdflatexがあっても、変化しないように。

そんな感じでお願いしてもよいでしょうか？

**Comment by aminophen** [comment]
ずいぶん時間が経ってしまいましたが， @norbert さんの代わりに c2dc3f3 で書いてみました。

TeXworks のデフォルトを

- LANG=ja
- デフォルトが何も設定されていない

のときに，pLaTeX (ptex2pdf) に変更します。

テストをお願いします。一応テスト方法は

~~~~
$ tlmgr postaction install script ptex2pdf
~~~~

を実行します。特に Mac と Linux では全く動かしていないので，書き込む TeXworks.ini の path は間違っていると思います。

**Comment by norbusan** [comment]
更新をありがとうございます。
ちょっと文句を活かせて：
```
+  # TODO: how to set the default on Mac and Linux (where is the config file) ? -- HY
+  if (!win32()) {
+    info("(ptex2pdf postinst: default setting is currently unsupported)");
+    return 0;
```
ということは、すべてのLinux/Macユーザをみせられてることになりますよね。

それはよくないと思います。Linuxならば、`$XDG_CONFIG_HOME/TUG/TeXworks.conf`なんですが、env var XDG_CONFIG_HOMEがなかったら、$HOME/.configを使われています。

MacOSの場合は、どうかな？

**Comment by aminophen** [comment]
コメントありがとうございます。その少し上の方の

~~~~ perl
   if (win32()) {
     chomp( my $twini = `kpsewhich -var-value=TW_INIPATH` ) ;
     $toolsdir = "$twini/configuration";
     $tugdir = "$twini/TUG";
   } elsif ($^O eq "darwin") {
     $toolsdir = $ENV{'HOME'} . "/Library/TeXworks/configuration";
     $tugdir = $ENV{'HOME'} . "/Library/TeXworks/TUG"; # This is wrong! -- HY
   } else {
     $toolsdir = $ENV{'HOME'} . "/.TeXworks/configuration";
     $tugdir = $ENV{'HOME'} . "/.TeXworks/TUG"; # This is wrong! -- HY
   }
~~~~

の directory を訂正できれば，Linux/Mac でも動くと思います。ただ，私は win32 以外を使っていないのでテストはできませんし，調べられません。どなたかお願いします。

なお私としては，install-tl で TeXworks がインストールされる (= TeXworks itself is contained in TeX Live) のは win32 だけなので，少なくとも win32 だけ動けば十分 meaningful だと思います。

**Comment by norbusan** [comment]
仕事が終わったらちょっとコードを書きます。
僕の方テストします。

最後の段落について：僕はTeXworksをDebianからインストールしましたから、このpostinstall scriptは使われています。他の人は同じ。
ですから、できるだけMac/Linux/Winを同様にしたいと思います。

**Comment by abenori** [comment]
Macの場合は上の方でdoraTeXさんが書かれている通りです．バイナリファイルなので直接編集できないため，ツールを介さないとならないのが要注意ですね．

**Comment by norbusan** [comment]
Linuxのコードを入れました。テストをしました。説明を書きました。
これでいいですか？TLに入れましょうか？

**Comment by aminophen** [comment]
ありがとうございます。TeX Live DVD に間に合ってほしいので、upload してくださると助かります。

**Comment by norbusan** [comment]
アップロードはいらないと思います。最後のバーションから何も変わっていません。
postcodeだけ自分でTLに入れます。

**Comment by norbusan** [comment]
TLにコミットしました。
